"""Orchestrator engine managing topological pipeline execution, dependency validations, and Celery task chain dispatching."""

from typing import Any, Callable, cast

from celery import chain, signature
from celery.canvas import Signature
from celery.result import AsyncResult

from app.config import settings
from app.schemas import (
    ExecutionState,
    PipelinePhase,
    PipelineRunRequest,
    SimulationManifest,
    TaskContext,
)
from app.services.state_manager import get_manifest, update_manifest
from app.workers.tasks import (
    run_lwr_pre_processing,
    run_lwr_simulation,
    run_post_processing,
    run_pre_processing,
    run_vf_computation,
)

# 1. Definitive Execution Topology & Field Mapping (Completely String-Free)
PIPELINE_TOPOLOGY = (
    (PipelinePhase.PRE_PROCESSING, lambda r: r.run_pre_processing, None),
    (PipelinePhase.VF_COMPUTATION, lambda r: r.run_vf_comp, PipelinePhase.PRE_PROCESSING),
    (
        PipelinePhase.LWR_PRE_PROCESSING,
        lambda r: r.run_lwr_preprocessing,
        PipelinePhase.VF_COMPUTATION,
    ),
    (
        PipelinePhase.LWR_SIMULATION,
        lambda r: r.run_lwr_simulation,
        PipelinePhase.LWR_PRE_PROCESSING,
    ),
    (PipelinePhase.POST_PROCESSING, lambda r: r.run_post_processing, PipelinePhase.LWR_SIMULATION),
)

TASK_MAP: dict[PipelinePhase, Callable[..., Any]] = {
    PipelinePhase.PRE_PROCESSING: run_pre_processing,
    PipelinePhase.VF_COMPUTATION: run_vf_computation,
    PipelinePhase.LWR_PRE_PROCESSING: run_lwr_pre_processing,
    PipelinePhase.LWR_SIMULATION: run_lwr_simulation,
    PipelinePhase.POST_PROCESSING: run_post_processing,
}


def _extract_ordered_phases(request: PipelineRunRequest) -> list[PipelinePhase]:
    """Evaluate request toggles against the execution matrix to derive an ordered phase list.

    Iterates through the structural pipeline topology matrix sequentially and evaluates
    the active request flags to determine which steps require scheduling.

    Args:
        request (PipelineRunRequest): Incoming data transfer schema tracking active
            execution phase boolean configurations.

    Returns:
        list[PipelinePhase]: Collection of filtered pipeline phases arranged in strict
            topological order.
    """
    return [phase for phase, check_flag, _ in PIPELINE_TOPOLOGY if check_flag(request)]


def _validate_execution_request(
    manifest: SimulationManifest, ordered_phases: list[PipelinePhase]
) -> bool:
    """Validate requested steps against concurrency locks and foundational prerequisites.

    Ensures at least one phase is active, scans the persistence manifest for ongoing
    asynchronous tasks, and evaluates structural prerequisite dependencies for the entry phase.

    Args:
        manifest (SimulationManifest): Workspace instance tracking current operational state.
        ordered_phases (list[PipelinePhase]): Collection of targeted pipeline phases arranged
            in execution sequence.

    Raises:
        ValueError: Raised if the ordered phase collection is empty.
        ValueError: Raised if any phase in the workspace manifest matches an active running or
            pending execution block state.
        ValueError: Raised if the foundational prerequisite step for the entry phase is missing
            or incomplete.

    Returns:
        bool: True if all system constraint boundaries are successfully verified.
    """
    # 1. Structural Guard: Ensure at least one phase toggle was flipped True
    if not ordered_phases:
        raise ValueError("No simulation phases were selected for execution.")

    # 2. Concurrency Guard: Block execution if an operation is active
    for phase, state in manifest.phase_statuses.items():
        if state in (ExecutionState.PENDING, ExecutionState.RUNNING):
            raise ValueError(
                f"Simulation workspace is locked: '{phase.value}' is currently {state.value}. "
                f"Please wait for active workers to complete."
            )

    # 3. Prerequisite Check for the entry-point step
    first_step = ordered_phases[0]
    prereq = next((p for phase, _, p in PIPELINE_TOPOLOGY if phase == first_step), None)

    if prereq is not None:
        if manifest.phase_statuses.get(prereq) != ExecutionState.COMPLETED:
            raise ValueError(
                f"Cannot execute '{first_step.value}'. "
                f"The foundational step '{prereq.value}' must be successfully completed first."
            )

    return True


def _set_task_queue(task_sig: Any, queue_name: str) -> Signature:
    """Safely cast and route a Celery task signature to an explicit infrastructure lane.

    Applies a type assertion wrapper over loose framework signature objects to satisfy
    static analysis enforcement while mutating the target broker queue property.

    Args:
        task_sig (Any): The raw unbound task signature generated by framework helpers.
        queue_name (str): Operational queue string name resolved from environment parameters.

    Returns:
        Signature: The strongly typed Celery Canvas signature instance bound to the target queue.
    """
    return cast(Signature, task_sig).set(queue=queue_name)


def _dispatch_chain(workflow: Any) -> str:
    """Fire the constructed Celery canvas workflow chain and verify brokerage tracking registration.

    Transmits the asynchronous execution pipeline to the configured message broker and
    asserts that a valid task identifiers tracking sequence is generated.

    Args:
        workflow (Any): Composed Celery canvas pipeline link chain object.

    Raises:
        RuntimeError: Raised if the message broker fails to return a valid execution tracking ID.

    Returns:
        str: Unique parent identifier string tracking the asynchronous chain workflow context.
    """
    result = cast(AsyncResult, workflow.apply_async())
    if not result.id:
        raise RuntimeError("Broker failed to provision an execution task ID.")
    return str(result.id)


def _get_dynamic_queue(priority_queue: bool) -> str:
    """Resolve the destination routing queue string utilizing application environment settings.

    Maps structural priority indicators directly to infrastructure parameters defined
    within the centralized configuration system.

    Args:
        priority_queue (bool): Indicator establishing if the task chain targets the accelerated
        execution lane.

    Returns:
        str: Target broker channel name resolved from environment variables.
    """
    if priority_queue:
        return settings.celery_fast_lane_queue

    return settings.celery_slow_lane_queue


def schedule_pipeline(user_id: str, sim_id: str, request: PipelineRunRequest) -> str:
    """Register request tasks as an async Celery workflow chain.

    Fetches the localized execution manifest file, evaluates activation toggles, asserts state
    safety boundaries, mutates workspace state indicators to pending initialization values,
    constructs the distributed signature chain passing the execution context block link, and
    dispatches the execution payload to the broker.

    Args:
        user_id (str): Unique user identifier owning the workspace context.
        sim_id (str): Unique simulation schema identifier.
        request (PipelineRunRequest): Data schema tracking active phase execution requests.

    Raises:
        ValueError: Raised if validation parameters fail against database boundaries or if no steps
        are selected.
        RuntimeError: Raised if message broker pipelines fail execution sequence tracking
        provisioning.

    Returns:
        str: Unique identifier string tracking the parent canvas chain task instance.
    """
    manifest = get_manifest(user_id, sim_id)
    ordered_phases = _extract_ordered_phases(request)

    _validate_execution_request(manifest, ordered_phases)

    # Update manifest queue state
    for phase in ordered_phases:
        manifest.phase_statuses[phase] = ExecutionState.PENDING
    update_manifest(user_id, sim_id, manifest)

    # Construct and dispatch Async Celery Chain
    context = TaskContext(user_id=user_id, simulation_id=sim_id)
    celery_chain_tasks = []
    queue_name = _get_dynamic_queue(request.priority_queue)

    for i, phase in enumerate(ordered_phases):
        task_func = TASK_MAP[phase]
        raw_sig = (
            signature(task_func, args=(context.model_dump(),)) if i == 0 else signature(task_func)
        )

        celery_chain_tasks.append(_set_task_queue(raw_sig, queue_name))

    return _dispatch_chain(chain(*celery_chain_tasks))
