# app/workers/tasks_lwr_pre.py
from celery import shared_task

# from my_core_package import lwr_matrix_builder
from app.schemas import PipelinePhase, TaskContext
from app.services.task_helpers import manage_task_state

# Define the identity of this specific worker file
CURRENT_PHASE = PipelinePhase.VF_COMP


@shared_task(bind=True)
def run_lwr_preprocessing(self, context: dict):
    """Generates thermal matrices for the long-wave radiation solver."""

    task_context = TaskContext(**context)

    # The context manager abstracts EVERYTHING.
    # If prerequisites fail, it raises an error before entering the block.
    # If the math crashes, it catches the error and marks the manifest FAILED.
    with manage_task_state(
        task_context.user_id, task_context.simulation_id, CURRENT_PHASE
    ) as manifest:
        None

        # --- THE ACTUAL ALGORITHM LOGIC ---

        # # 1. Read input files generated by the previous step
        # vf_file = manifest.output_files.get("vf_comp_output")

        # # 2. Extract strictly the configuration needed for this step
        # config = manifest.config.lwr_preprocessing

        # # 3. Execute the heavy computation
        # matrix_output_path = lwr_matrix_builder.process(
        #     vf_file_path=vf_file, generate_matrices=config.generate_thermal_matrices
        # )

        # # 4. Update the manifest with the new outputs
        # manifest.output_files["lwr_preprocessing_output"] = matrix_output_path

        # ----------------------------------

    # Pass the context down the Celery chain
    return task_context.model_dump()
